apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: test-k8
  namespace: aso-system
spec:
  location: canadaeast
  tags:
    environment: DEV

---

apiVersion: documentdb.azure.com/v1api20231115
kind: DatabaseAccount
metadata:
  name: test-k8-cosmos
  namespace: aso-system
spec:
  location: canadaeast
  owner:
    name: test-k8
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: canadaeast
  consistencyPolicy:
    defaultConsistencyLevel: Session
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: azure-keys
        key: cosmos-key

---

apiVersion: documentdb.azure.com/v1api20231115
kind: SqlDatabase
metadata:
  name: test-db
  namespace: aso-system
spec:
  location: canadaeast
  owner:
    name: test-k8-cosmos
  resource:
    id: test-db
  options:
    autoscaleSettings:
      maxThroughput: 400