apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: test-aso
  namespace: azure-resources
spec:
  location: canadacentral
  tags:
    environment: DEV

---

apiVersion: documentdb.azure.com/v1api20231115
kind: DatabaseAccount
metadata:
  name: autio-cosmos-db
  namespace: azure-resources
spec:
  location: canadacentral
  owner:
    name: test-aso
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: canadacentral
  consistencyPolicy:
    defaultConsistencyLevel: Session
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: azure-keys
        key: cosmos-key

---

apiVersion: documentdb.azure.com/v1api20231115
kind: SqlDatabase
metadata:
  name: test-db
  namespace: azure-resources
spec:
  location: canadacentral
  owner:
    name: autio-cosmos-db
  resource:
    id: test-db
  options:
    autoscaleSettings:
      maxThroughput: 100