apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: test-k8-rg
  namespace: aso-system
spec:
  location: canadaeast
  tags:
    environment: DEV
  
---

apiVersion: microsoft.containerregistry.azure.com/v1beta1
kind: ContainerRegistry
metadata:
  name: testk8aksregistry
  namespace: aso-system
spec:
  location: canadaeast
  sku: Basic
  resourceGroup: test-k8-rg
  adminUserEnabled: true
  
---

apiVersion: documentdb.azure.com/v1api20231115
kind: DatabaseAccount
metadata:
  name: test-k8-cosmos
  namespace: aso-system
spec:
  location: canadaeast
  owner:
    name: test-k8-rg
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: canadaeast
  consistencyPolicy:
    defaultConsistencyLevel: Session
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: azure-keys
        key: cosmos-key

---

apiVersion: documentdb.azure.com/v1api20231115
kind: SqlDatabase
metadata:
  name: test-k8-rg
  namespace: aso-system
spec:
  location: canadaeast
  owner:
    name: test-k8-cosmos
  resource:
    id: test-db
  options:
    autoscaleSettings:
      maxThroughput: 400