apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: asdc-secret-vault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "12997213-780c-4898-bd90-724ae1088bad"
    keyvaultName: asdc-vault
    
    object: |
      array:
        - |
          objectName: test
          objectType: secret
    tenantId: "f095723a-5c76-4be6-a448-c51b49214e22"