apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: test-api
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: other-service
spec:
  selector:
    app: other-api
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: "/v1(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 7002
          - path: "/v2(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: other-service
                port:
                  number: 7001