apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_test-k8-rg_test-k8-cluster_canadaeast
    service.beta.kubernetes.io/azure-pip-name: aksPublicIP
    service.beta.kubernetes.io/azure-dns-label-name: asdc
  name: azure-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azure-load-balancer