name: Setup Azure Resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  setup-azure:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest
          
      - name: Install kubelogin
        run: |
          sudo az aks install-cli  # This installs kubectl if not already installed
          sudo apt-get install kubelogin -y  # Install kubelogin for AAD auth
                
      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group autio-web --name test-k8 --overwrite-existing        
          kubectl apply -f workflows/aso.yml
          kubectl get all -n default
          kubectl wait --for=condition=Ready sqldatabase/test-db