name: Setup Azure Resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  setup-azure:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-main
      cancel-in-progress: false
      
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Login to Azure
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'
          
      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group autio-web --name test-k8
          
      - name: Ensure proper context
        run: |
          kubectl config get-contexts 
          
      - name: Test
        run: |
          kubectl get nodes
          
    