name: Setup Azure Resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  setup-azure:
    runs-on: ubuntu-latest
      
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Login to Azure using Service Principal
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Install kubelogin
        uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'
        
      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group test-k8-rg --name test-k8-aks --overwrite-existing

      - name: Set up kubelogin for non-interactive login
        run: |
          kubelogin convert-kubeconfig -l azurecli
          
      - name: Install Cert Manager using Helm
        run: |
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --set crds.enabled=true
          
      - name: Install ASO using Helm
        run: |
          helm repo add aso2 https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
          helm repo update
          helm upgrade --install azure-service-operator aso2/azure-service-operator \
            --create-namespace \
            --namespace aso-system \
            --set crds.enabled=true \
            --set crdPattern='resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*;documentdb.azure.com/*'                           
        
      - name: Apply K8 manifests
        run: |
          kubectl apply -f workflows/aso.yml

      - name: Verify ASO Resources
        run: |
          kubectl -n aso-system get all
          
      - name: Login to Container Registry
        run: |
          az acr login --name testk8registry

      - name: Build K8Test image
        working-directory: K8Test
        run: |
          docker build -t testk8registry/k8test-api .
          docker push testk8registry/k8test-api
          
      - name: Build K8OtherApi image
        working-directory: K8OtherAPI
        run: |
          docker build -t testk8registry/k8other-api .
          docker push testk8registry/k8other-api
          
      - name: Deploy API manifests
        run: |
          kubectl apply -f workflows/deployments.yml
          
    